//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Food4FunEngine.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.Recipes = new HashSet<Recipe>();
        }
    
        public System.Guid CountryID { get; private set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
    
        public virtual ICollection<Recipe> Recipes { get; set; }
    }
}
