//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Food4FunEngine.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient
    {
        public Ingredient()
        {
            this.Recipes = new HashSet<Recipe>();
        }
    
        public System.Guid Id { get; private set; }
        public string Name { get; set; }
        public decimal Carbs { get; set; }
        public decimal Fat { get; set; }
        public decimal Protein { get; set; }
        public string Description { get; set; }
        public string PictureUrl { get; set; }
        public Nullable<RecipeOriginCountry> OriginCountry { get; set; }
    
        public virtual ICollection<Recipe> Recipes { get; set; }
    }
}
