//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Food4FunEngine.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient
    {
        public Ingredient()
        {
            this.Pictures = new HashSet<Picture>();
            this.Recipes = new HashSet<Recipe>();
        }
    
        public System.Guid IngredientID { get; private set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal FatPr100g { get; set; }
        public decimal CarbsPr100g1 { get; set; }
        public decimal ProteinPr100g2 { get; set; }
    
        public virtual ICollection<Picture> Pictures { get; set; }
        public virtual ICollection<Recipe> Recipes { get; set; }
    }
}
