//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Food4FunEngine.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.Pictures = new HashSet<Picture>();
            this.Dishes = new HashSet<Dish>();
        }
    
        public System.Guid MenuID { get; private set; }
        public string Name { get; set; }
    
        public virtual ICollection<Picture> Pictures { get; set; }
        public virtual ICollection<Dish> Dishes { get; set; }
    }
}
