//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Food4FunEngine.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        public Recipe()
        {
            this.Dishes = new HashSet<Dish>();
            this.AmountOfIngrdients = new HashSet<AmountOf>();
        }
    
        public System.Guid RecipeID { get; private set; }
        public string Name { get; set; }
        public string WorkDescription { get; set; }
        public System.TimeSpan PrepTime { get; set; }
    
        public virtual ICollection<Dish> Dishes { get; set; }
        public virtual Country Country { get; set; }
        public virtual ICollection<AmountOf> AmountOfIngrdients { get; set; }
    }
}
